"""Best params for each model phase by model"""

best_SVC_params_by_label = {'Eye disorders': {'svc__C': 0.1,
                                              'svc__gamma': 0.1,
                                              'svc__kernel': 'rbf'},
                            'Gastrointestinal disorders': {'svc__C': 0.01,
                                                           'svc__gamma': 1,
                                                           'svc__kernel': 'rbf'},
                            'Hepatobiliary disorders': {'svc__C': 10,
                                                        'svc__gamma': 0.1,
                                                        'svc__kernel': 'rbf'},
                            'Metabolism and nutrition disorders': {'svc__C': 0.01,
                                                                   'svc__gamma': 1,
                                                                   'svc__kernel': 'rbf'},
                            'Musculoskeletal and connective tissue disorders': {'svc__C': 10,
                                                                                'svc__gamma': 1,
                                                                                'svc__kernel': 'rbf'},
                            'Endocrine disorders': {'svc__C': 0.01,
                                                    'svc__gamma': 0.001,
                                                    'svc__kernel': 'rbf'},
                            'General disorders and administration site conditions': {'svc__C': 0.01,
                                                                                     'svc__gamma': 1,
                                                                                     'svc__kernel': 'rbf'},
                            'Immune system disorders': {'svc__C': 0.01,
                                                        'svc__gamma': 0.1,
                                                        'svc__kernel': 'rbf'},
                            'Neoplasms benign, malignant and unspecified (incl cysts and polyps)': {'svc__C': 10,
                                                                                                    'svc__gamma': 0.01,
                                                                                                    'svc__kernel': 'rbf'},
                            'Reproductive system and breast disorders': {'svc__C': 10,
                                                                         'svc__gamma': 0.1,
                                                                         'svc__kernel': 'rbf'},
                            'Blood and lymphatic system disorders': {'svc__C': 0.01,
                                                                     'svc__gamma': 1,
                                                                     'svc__kernel': 'rbf'},
                            'Congenital, familial and genetic disorders': {'svc__C': 0.01,
                                                                           'svc__gamma': 0.001,
                                                                           'svc__kernel': 'rbf'},
                            'Infections and infestations': {'svc__C': 0.01,
                                                            'svc__gamma': 1,
                                                            'svc__kernel': 'rbf'},
                            'Pregnancy, puerperium and perinatal conditions': {'svc__C': 10,
                                                                               'svc__gamma': 0.01,
                                                                               'svc__kernel': 'rbf'},
                            'Psychiatric disorders': {'svc__C': 1,
                                                      'svc__gamma': 1,
                                                      'svc__kernel': 'rbf'},
                            'Renal and urinary disorders': {'svc__C': 0.1,
                                                            'svc__gamma': 0.1,
                                                            'svc__kernel': 'rbf'},
                            'Respiratory, thoracic and mediastinal disorders': {'svc__C': 0.01,
                                                                                'svc__gamma': 1,
                                                                                'svc__kernel': 'rbf'},
                            'Skin and subcutaneous tissue disorders': {'svc__C': 0.01,
                                                                       'svc__gamma': 1,
                                                                       'svc__kernel': 'rbf'},
                            'Surgical and medical procedures': {'svc__C': 1,
                                                                'svc__gamma': 0.001,
                                                                'svc__kernel': 'rbf'},
                            'Vascular disorders': {'svc__C': 0.01,
                                                   'svc__gamma': 1,
                                                   'svc__kernel': 'rbf'},
                            'Cardiac disorders': {'svc__C': 0.01,
                                                  'svc__gamma': 1,
                                                  'svc__kernel': 'rbf'},
                            'Ear and labyrinth disorders': {'svc__C': 1,
                                                            'svc__gamma': 0.001,
                                                            'svc__kernel': 'rbf'},
                            'Injury, poisoning and procedural complications': {'svc__C': 0.01,
                                                                               'svc__gamma': 1,
                                                                               'svc__kernel': 'rbf'},
                            'Nervous system disorders': {'svc__C': 1,
                                                         'svc__gamma': 1,
                                                         'svc__kernel': 'rbf'}}

best_RF_params_by_label_random = {'Eye disorders': {'randomforestclassifier__bootstrap': False,
                                                    'randomforestclassifier__max_depth': 210,
                                                    'randomforestclassifier__max_features': 'log2',
                                                    'randomforestclassifier__min_samples_leaf': 1,
                                                    'randomforestclassifier__min_samples_split': 10,
                                                    'randomforestclassifier__n_estimators': 400},
                                  'Gastrointestinal disorders': {'randomforestclassifier__bootstrap': False,
                                                                 'randomforestclassifier__max_depth': 170,
                                                                 'randomforestclassifier__max_features': 'log2',
                                                                 'randomforestclassifier__min_samples_leaf': 1,
                                                                 'randomforestclassifier__min_samples_split': 10,
                                                                 'randomforestclassifier__n_estimators': 1000},
                                  'Hepatobiliary disorders': {'randomforestclassifier__bootstrap': True,
                                                              'randomforestclassifier__max_depth': 210,
                                                              'randomforestclassifier__max_features': 'sqrt',
                                                              'randomforestclassifier__min_samples_leaf': 1,
                                                              'randomforestclassifier__min_samples_split': 10,
                                                              'randomforestclassifier__n_estimators': 200},
                                  'Metabolism and nutrition disorders': {'randomforestclassifier__bootstrap': False,
                                                                         'randomforestclassifier__max_depth': 130,
                                                                         'randomforestclassifier__max_features': 'sqrt',
                                                                         'randomforestclassifier__min_samples_leaf': 1,
                                                                         'randomforestclassifier__min_samples_split': 5,
                                                                         'randomforestclassifier__n_estimators': 400},
                                  'Musculoskeletal and connective tissue disorders': {
                                      'randomforestclassifier__bootstrap': False,
                                      'randomforestclassifier__max_depth': 250,
                                      'randomforestclassifier__max_features': 'log2',
                                      'randomforestclassifier__min_samples_leaf': 1,
                                      'randomforestclassifier__min_samples_split': 10,
                                      'randomforestclassifier__n_estimators': 300},
                                  'Endocrine disorders': {'randomforestclassifier__bootstrap': False,
                                                          'randomforestclassifier__max_depth': 250,
                                                          'randomforestclassifier__max_features': 'log2',
                                                          'randomforestclassifier__min_samples_leaf': 1,
                                                          'randomforestclassifier__min_samples_split': 2,
                                                          'randomforestclassifier__n_estimators': 100},
                                  'General disorders and administration site conditions': {
                                      'randomforestclassifier__bootstrap': False,
                                      'randomforestclassifier__max_depth': 170,
                                      'randomforestclassifier__max_features': 'log2',
                                      'randomforestclassifier__min_samples_leaf': 1,
                                      'randomforestclassifier__min_samples_split': 2,
                                      'randomforestclassifier__n_estimators': 200},
                                  'Immune system disorders': {'randomforestclassifier__bootstrap': True,
                                                              'randomforestclassifier__max_depth': 90,
                                                              'randomforestclassifier__max_features': 'sqrt',
                                                              'randomforestclassifier__min_samples_leaf': 1,
                                                              'randomforestclassifier__min_samples_split': 5,
                                                              'randomforestclassifier__n_estimators': 700},
                                  'Neoplasms benign, malignant and unspecified (incl cysts and polyps)': {
                                      'randomforestclassifier__bootstrap': False,
                                      'randomforestclassifier__max_depth': 170,
                                      'randomforestclassifier__max_features': 'sqrt',
                                      'randomforestclassifier__min_samples_leaf': 1,
                                      'randomforestclassifier__min_samples_split': 2,
                                      'randomforestclassifier__n_estimators': 800},
                                  'Reproductive system and breast disorders': {
                                      'randomforestclassifier__bootstrap': False,
                                      'randomforestclassifier__max_depth': 50,
                                      'randomforestclassifier__max_features': 'sqrt',
                                      'randomforestclassifier__min_samples_leaf': 1,
                                      'randomforestclassifier__min_samples_split': 10,
                                      'randomforestclassifier__n_estimators': 200},
                                  'Surgical and medical procedures': {'randomforestclassifier__n_estimators': 200,
                                                                      'randomforestclassifier__min_samples_split': 5,
                                                                      'randomforestclassifier__min_samples_leaf': 1,
                                                                      'randomforestclassifier__max_features': 'sqrt',
                                                                      'randomforestclassifier__max_depth': 130,
                                                                      'randomforestclassifier__bootstrap': False}}
