''' Best params for each model phase by model '''

best_SVC_params_by_label = {'Blood and lymphatic system disorders': {'C': 10,
                                          'gamma': 0.1,
                                          'kernel': 'rbf'},
 'Cardiac disorders': {'C': 100,
                       'gamma': 0.1,
                       'kernel': 'rbf'},
 'Congenital, familial and genetic disorders': {'C': 10,
                                                'gamma': 0.1,
                                                'kernel': 'rbf'},
 'Ear and labyrinth disorders': {'C': 100,
                                 'gamma': 0.01,
                                 'kernel': 'rbf'},
 'Endocrine disorders': {'C': 1,
                         'gamma': 0.1,
                         'kernel': 'rbf'},
 'Eye disorders': {'C': 10,
                   'gamma': 0.1,
                   'kernel': 'rbf'},
 'Gastrointestinal disorders': {'C': 10,
                                'gamma': 0.1,
                                'kernel': 'rbf'},
 'General disorders and administration site conditions': {'C': 10,
                                                          'gamma': 0.1,
                                                          'kernel': 'rbf'},
 'Hepatobiliary disorders': {'C': 1,
                             'gamma': 0.1,
                             'kernel': 'rbf'},
 'Immune system disorders': {'C': 10,
                             'gamma': 0.1,
                             'kernel': 'rbf'},
 'Infections and infestations': {'C': 10,
                                 'gamma': 0.1,
                                 'kernel': 'rbf'},
 'Injury, poisoning and procedural complications': {'C': 10,
                                                    'gamma': 0.1,
                                                    'kernel': 'rbf'},
 'Metabolism and nutrition disorders': {'C': 10,
                                        'gamma': 0.1,
                                        'kernel': 'rbf'},
 'Musculoskeletal and connective tissue disorders': {'C': 10,
                                                     'gamma': 0.1,
                                                     'kernel': 'rbf'},
 'Neoplasms benign, malignant and unspecified (incl cysts and polyps)': {'C': 10,
                                                                         'gamma': 0.1,
                                                                         'kernel': 'rbf'},
 'Nervous system disorders': {'C': 100,
                              'gamma': 0.1,
                              'kernel': 'rbf'},
 'Pregnancy, puerperium and perinatal conditions': {'C': 10,
                                                    'gamma': 0.1,
                                                    'kernel': 'rbf'},
 'Psychiatric disorders': {'C': 10,
                           'gamma': 0.1,
                           'kernel': 'rbf'},
 'Renal and urinary disorders': {'C': 100,
                                 'gamma': 0.1,
                                 'kernel': 'rbf'},
 'Reproductive system and breast disorders': {'C': 10,
                                              'gamma': 0.1,
                                              'kernel': 'rbf'},
 'Respiratory, thoracic and mediastinal disorders': {'C': 10,
                                                     'gamma': 0.1,
                                                     'kernel': 'rbf'},
 'Skin and subcutaneous tissue disorders': {'C': 10,
                                            'gamma': 0.1,
                                            'kernel': 'rbf'},
 'Surgical and medical procedures': {'C': 0.1,
                                     'gamma': 0.0001,
                                     'kernel': 'linear'},
 'Vascular disorders': {'C': 10,
                        'gamma': 0.1,
                        'kernel': 'rbf'}}

best_RF_params_by_label_random = {'Blood and lymphatic system disorders': {'bootstrap': True,
                                          'max_depth': 190,
                                          'max_features': 'log2',
                                          'min_samples_leaf': 1,
                                          'min_samples_split': 2,
                                          'n_estimators': 200},
 'Cardiac disorders': {'bootstrap': False,
                       'max_depth': 210,
                       'max_features': 'log2',
                       'min_samples_leaf': 1,
                       'min_samples_split': 2,
                       'n_estimators': 600},
 'Congenital, familial and genetic disorders': {'bootstrap': False,
                                                'max_depth': 170,
                                                'max_features': 'sqrt',
                                                'min_samples_leaf': 1,
                                                'min_samples_split': 5,
                                                'n_estimators': 400},
 'Ear and labyrinth disorders': {'bootstrap': False,
                                 'max_depth': 190,
                                 'max_features': 'sqrt',
                                 'min_samples_leaf': 1,
                                 'min_samples_split': 20,
                                 'n_estimators': 1000},
 'Endocrine disorders': {'bootstrap': False,
                         'max_depth': 230,
                         'max_features': 'log2',
                         'min_samples_leaf': 1,
                         'min_samples_split': 2,
                         'n_estimators': 200},
 'Eye disorders': {'bootstrap': False,
                   'max_depth': 70,
                   'max_features': 'log2',
                   'min_samples_leaf': 1,
                   'min_samples_split': 5,
                   'n_estimators': 800},
 'Gastrointestinal disorders': {'bootstrap': False,
                                'max_depth': 70,
                                'max_features': 'sqrt',
                                'min_samples_leaf': 1,
                                'min_samples_split': 5,
                                'n_estimators': 800},
 'General disorders and administration site conditions': {'bootstrap': False,
                                                          'max_depth': 170,
                                                          'max_features': 'log2',
                                                          'min_samples_leaf': 1,
                                                          'min_samples_split': 2,
                                                          'n_estimators': 1000},
 'Hepatobiliary disorders': {'bootstrap': True,
                             'max_depth': 110,
                             'max_features': 'log2',
                             'min_samples_leaf': 1,
                             'min_samples_split': 5,
                             'n_estimators': 600},
 'Immune system disorders': {'bootstrap': True,
                             'max_depth': 90,
                             'max_features': 'log2',
                             'min_samples_leaf': 1,
                             'min_samples_split': 5,
                             'n_estimators': 700},
 'Infections and infestations': {'bootstrap': True,
                                 'max_depth': 90,
                                 'max_features': 'log2',
                                 'min_samples_leaf': 1,
                                 'min_samples_split': 10,
                                 'n_estimators': 1000},
 'Injury, poisoning and procedural complications': {'bootstrap': False,
                                                    'max_depth': 190,
                                                    'max_features': 'log2',
                                                    'min_samples_leaf': 1,
                                                    'min_samples_split': 2,
                                                    'n_estimators': 400},
 'Metabolism and nutrition disorders': {'bootstrap': True,
                                        'max_depth': 190,
                                        'max_features': 'sqrt',
                                        'min_samples_leaf': 1,
                                        'min_samples_split': 10,
                                        'n_estimators': 400},
 'Musculoskeletal and connective tissue disorders': {'bootstrap': False,
                                                     'max_depth': 150,
                                                     'max_features': 'log2',
                                                     'min_samples_leaf': 1,
                                                     'min_samples_split': 5,
                                                     'n_estimators': 200},
 'Neoplasms benign, malignant and unspecified (incl cysts and polyps)': {'bootstrap': False,
                                                                         'max_depth': 210,
                                                                         'max_features': 'sqrt',
                                                                         'min_samples_leaf': 1,
                                                                         'min_samples_split': 2,
                                                                         'n_estimators': 400},
 'Nervous system disorders': {'bootstrap': False,
                              'max_depth': None,
                              'max_features': 'log2',
                              'min_samples_leaf': 1,
                              'min_samples_split': 5,
                              'n_estimators': 300},
 'Pregnancy, puerperium and perinatal conditions': {'bootstrap': True,
                                                    'max_depth': 210,
                                                    'max_features': 'sqrt',
                                                    'min_samples_leaf': 1,
                                                    'min_samples_split': 2,
                                                    'n_estimators': 400},
 'Psychiatric disorders': {'bootstrap': False,
                           'max_depth': 190,
                           'max_features': 'log2',
                           'min_samples_leaf': 1,
                           'min_samples_split': 10,
                           'n_estimators': 800},
 'Renal and urinary disorders': {'bootstrap': False,
                                 'max_depth': 50,
                                 'max_features': 'log2',
                                 'min_samples_leaf': 2,
                                 'min_samples_split': 5,
                                 'n_estimators': 400},
 'Reproductive system and breast disorders': {'bootstrap': False,
                                              'max_depth': 170,
                                              'max_features': 'sqrt',
                                              'min_samples_leaf': 5,
                                              'min_samples_split': 5,
                                              'n_estimators': 200},
 'Respiratory, thoracic and mediastinal disorders': {'bootstrap': True,
                                                     'max_depth': 210,
                                                     'max_features': 'log2',
                                                     'min_samples_leaf': 1,
                                                     'min_samples_split': 5,
                                                     'n_estimators': 500},
 'Skin and subcutaneous tissue disorders': {'bootstrap': False,
                                            'max_depth': 150,
                                            'max_features': 'log2',
                                            'min_samples_leaf': 1,
                                            'min_samples_split': 5,
                                            'n_estimators': 900},
 'Surgical and medical procedures': {'bootstrap': False,
                                     'max_depth': 110,
                                     'max_features': 'sqrt',
                                     'min_samples_leaf': 1,
                                     'min_samples_split': 5,
                                     'n_estimators': 400},
 'Vascular disorders': {'bootstrap': False,
                        'max_depth': 170,
                        'max_features': 'log2',
                        'min_samples_leaf': 1,
                        'min_samples_split': 5,
                        'n_estimators': 900}}

rf_params_to_grid = {'Blood and lymphatic system disorders': {'bootstrap': [True, False],
                                          'max_depth': [160, 190, 220],
                                          'max_features': ["log2", "sqrt"],
                                          'min_samples_leaf': [1, 2, 5],
                                          'min_samples_split': [2, 5, 10],
                                          'n_estimators': [170, 200, 230]},
 'Cardiac disorders': {'bootstrap': [True, False],
                       'max_depth': [180, 210, 240],
                       'max_features': ["log2", "sqrt"],
                       'min_samples_leaf': [1, 2],
                       'min_samples_split': [2, 5, 10],
                       'n_estimators': [570, 600, 630]},
 'Congenital, familial and genetic disorders': {'bootstrap': [True, False],
                                                'max_depth': [140, 170, 200],
                                                'max_features': ["log2", "sqrt"],
                                                'min_samples_leaf': [1, 2, 5],
                                                'min_samples_split': [2, 5, 10],
                                                'n_estimators': [370, 400, 430]},
 'Ear and labyrinth disorders': {'bootstrap': [True, False],
                                 'max_depth': [160, 190, 220],
                                 'max_features': ["log2", "sqrt"],
                                 'min_samples_leaf': [1, 2, 5],
                                 'min_samples_split': [2, 5, 10],
                                 'n_estimators': [970, 1000, 1030]},
 'Endocrine disorders': {'bootstrap': [True, False],
                         'max_depth': [200, 230, 260],
                         'max_features': ["log2", "sqrt"],
                         'min_samples_leaf': [1, 2, 5],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [170, 200, 230]},
 'Eye disorders': {'bootstrap': [True, False],
                   'max_depth': [40, 70, 100],
                   'max_features': ["log2", "sqrt"],
                   'min_samples_leaf': [1, 2, 5],
                   'min_samples_split': [2, 5, 10],
                   'n_estimators': [770, 800, 830]},
 'Gastrointestinal disorders': {'bootstrap': [True, False],
                                'max_depth': [40, 70, 100],
                                'max_features': ["log2", "sqrt"],
                                'min_samples_leaf': [1, 2, 5],
                                'min_samples_split': [2, 5, 10],
                                'n_estimators': [770, 800, 830]},
 'General disorders and administration site conditions': {'bootstrap': [True, False],
                                                          'max_depth': [140, 170, 200],
                                                          'max_features': ["log2", "sqrt"],
                                                          'min_samples_leaf': [1, 2, 5],
                                                          'min_samples_split': [2, 5, 10],
                                                          'n_estimators': [970, 1000, 1030]},
 'Hepatobiliary disorders': {'bootstrap': [True, False],
                             'max_depth': [80, 110, 140],
                             'max_features': ["log2", "sqrt"],
                             'min_samples_leaf': [1, 2, 5],
                             'min_samples_split': [2, 5, 10],
                             'n_estimators': [570, 600, 630]},
 'Immune system disorders': {'bootstrap': [True, False],
                             'max_depth': [60, 90, 120],
                             'max_features': ["log2", "sqrt"],
                             'min_samples_leaf': [1, 2, 5],
                             'min_samples_split': [2, 5, 10],
                             'n_estimators': [670, 700, 730]},
 'Infections and infestations': {'bootstrap': [True, False],
                                 'max_depth': [60, 90, 120],
                                 'max_features': ["log2", "sqrt"],
                                 'min_samples_leaf': [1, 2, 5],
                                 'min_samples_split': [2, 5, 10],
                                 'n_estimators': [970, 1000, 1030]},
 'Injury, poisoning and procedural complications': {'bootstrap': [True, False],
                                                    'max_depth': [160, 190, 220],
                                                    'max_features': ["log2", "sqrt"],
                                                    'min_samples_leaf': [1, 2, 5],
                                                    'min_samples_split': [2, 5, 10],
                                                    'n_estimators': [370, 400, 430]},
 'Metabolism and nutrition disorders': {'bootstrap': [True, False],
                                        'max_depth': [160, 190, 220],
                                        'max_features': ["log2", "sqrt"],
                                        'min_samples_leaf':[1, 2, 5],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [370, 400, 430]},
 'Musculoskeletal and connective tissue disorders': {'bootstrap': [True, False],
                                                     'max_depth': [120, 150, 180],
                                                     'max_features': ["log2", "sqrt"],
                                                     'min_samples_leaf': [1, 2, 5],
                                                     'min_samples_split': [2, 5, 10],
                                                     'n_estimators': [170, 200, 230]},
 'Neoplasms benign, malignant and unspecified (incl cysts and polyps)': {'bootstrap': [True, False],
                                                                         'max_depth': [180, 210, 240],
                                                                         'max_features': ["log2", "sqrt"],
                                                                         'min_samples_leaf': [1, 2, 5],
                                                                         'min_samples_split': [2, 5, 10],
                                                                         'n_estimators': [370, 400, 430]},
 'Nervous system disorders': {'bootstrap': [True, False],
                              'max_depth': [None, 100, 150, 200],
                              'max_features': ["log2", "sqrt"],
                              'min_samples_leaf': [1, 2, 5],
                              'min_samples_split': [2, 5, 10],
                              'n_estimators': [270, 300, 330]},
 'Pregnancy, puerperium and perinatal conditions': {'bootstrap': [True, False],
                                                    'max_depth': [180, 210, 240],
                                                    'max_features': ["log2", "sqrt"],
                                                    'min_samples_leaf': [1, 2, 5],
                                                    'min_samples_split': [2, 5, 10],
                                                    'n_estimators': [370, 400, 430]},
 'Psychiatric disorders': {'bootstrap': [True, False],
                           'max_depth': [160, 190, 220],
                           'max_features': ["log2", "sqrt"],
                           'min_samples_leaf': [1, 2, 5],
                           'min_samples_split': [2, 5, 10],
                           'n_estimators': [770, 800, 830]},
 'Renal and urinary disorders': {'bootstrap': [True, False],
                                 'max_depth': [60, 90, 120],
                                 'max_features': ["log2", "sqrt"],
                                 'min_samples_leaf': [1, 2, 5],
                                 'min_samples_split': [2, 5, 10],
                                 'n_estimators': [370, 400, 430]},
 'Reproductive system and breast disorders': {'bootstrap': [True, False],
                                              'max_depth': [140, 170, 160],
                                              'max_features': ["log2", "sqrt"],
                                              'min_samples_leaf': [1, 2, 5],
                                              'min_samples_split': [2, 5, 10],
                                              'n_estimators': [170, 200, 230]},
 'Respiratory, thoracic and mediastinal disorders': {'bootstrap': [True, False],
                                                     'max_depth': [180, 210, 240],
                                                     'max_features': ["log2", "sqrt"],
                                                     'min_samples_leaf': [1, 2, 5],
                                                     'min_samples_split': [2, 5, 10],
                                                     'n_estimators': [470, 500, 530]},
 'Skin and subcutaneous tissue disorders': {'bootstrap': [True, False],
                                            'max_depth': [120, 150, 180],
                                            'max_features': ["log2", "sqrt"],
                                            'min_samples_leaf': [1, 2, 5],
                                            'min_samples_split': [2, 5, 10],
                                            'n_estimators': [870, 900, 930]},
 'Surgical and medical procedures': {'bootstrap': [True, False],
                                     'max_depth': [80, 110, 140],
                                     'max_features': ["log2", "sqrt"],
                                     'min_samples_leaf': [1, 2, 5],
                                     'min_samples_split': [2, 5, 10],
                                     'n_estimators': [370, 400, 430]},
 'Vascular disorders': {'bootstrap': [True, False],
                        'max_depth': [140, 170, 200],
                        'max_features': ["log2", "sqrt"],
                        'min_samples_leaf': [1, 2, 5],
                        'min_samples_split': [2, 5, 10],
                        'n_estimators': [870, 900, 930]}}

best_RF_params_by_label_grid = {'Blood and lymphatic system disorders': {'bootstrap': True,
                                          'max_depth': 160,
                                          'max_features': 'log2',
                                          'min_samples_leaf': 1,
                                          'min_samples_split': 2,
                                          'n_estimators': 230},
 'Cardiac disorders': {'bootstrap': False,
                       'max_depth': 180,
                       'max_features': 'log2',
                       'min_samples_leaf': 1,
                       'min_samples_split': 2,
                       'n_estimators': 600},
 'Congenital, familial and genetic disorders': {'bootstrap': False,
                                                'max_depth': 140,
                                                'max_features': 'log2',
                                                'min_samples_leaf': 1,
                                                'min_samples_split': 5,
                                                'n_estimators': 370},
 'Ear and labyrinth disorders': {'bootstrap': False,
                                 'max_depth': 160,
                                 'max_features': 'sqrt',
                                 'min_samples_leaf': 1,
                                 'min_samples_split': 10,
                                 'n_estimators': 1030},
 'Endocrine disorders': {'bootstrap': False,
                         'max_depth': 200,
                         'max_features': 'sqrt',
                         'min_samples_leaf': 1,
                         'min_samples_split': 5,
                         'n_estimators': 230},
 'Eye disorders': {'bootstrap': False,
                   'max_depth': 70,
                   'max_features': 'log2',
                   'min_samples_leaf': 1,
                   'min_samples_split': 2,
                   'n_estimators': 770},
 'Gastrointestinal disorders': {'bootstrap': False,
                                'max_depth': 70,
                                'max_features': 'sqrt',
                                'min_samples_leaf': 1,
                                'min_samples_split': 5,
                                'n_estimators': 770},
 'General disorders and administration site conditions': {'bootstrap': False,
                                                          'max_depth': 140,
                                                          'max_features': 'log2',
                                                          'min_samples_leaf': 1,
                                                          'min_samples_split': 2,
                                                          'n_estimators': 1000},
 'Hepatobiliary disorders': {'bootstrap': True,
                             'max_depth': 80,
                             'max_features': 'log2',
                             'min_samples_leaf': 1,
                             'min_samples_split': 5,
                             'n_estimators': 570},
 'Immune system disorders': {'bootstrap': True,
                             'max_depth': 90,
                             'max_features': 'log2',
                             'min_samples_leaf': 1,
                             'min_samples_split': 5,
                             'n_estimators': 730},
 'Infections and infestations': {'bootstrap': True,
                                 'max_depth': 120,
                                 'max_features': 'log2',
                                 'min_samples_leaf': 1,
                                 'min_samples_split': 10,
                                 'n_estimators': 1030},
 'Injury, poisoning and procedural complications': {'bootstrap': False,
                                                    'max_depth': 160,
                                                    'max_features': 'log2',
                                                    'min_samples_leaf': 1,
                                                    'min_samples_split': 2,
                                                    'n_estimators': 400},
 'Metabolism and nutrition disorders': {'bootstrap': True,
                                        'max_depth': 160,
                                        'max_features': 'log2',
                                        'min_samples_leaf': 1,
                                        'min_samples_split': 5,
                                        'n_estimators': 370},
 'Musculoskeletal and connective tissue disorders': {'bootstrap': False,
                                                     'max_depth': 120,
                                                     'max_features': 'sqrt',
                                                     'min_samples_leaf': 1,
                                                     'min_samples_split': 5,
                                                     'n_estimators': 200},
 'Neoplasms benign, malignant and unspecified (incl cysts and polyps)': {'bootstrap': False,
                                                                         'max_depth': 180,
                                                                         'max_features': 'sqrt',
                                                                         'min_samples_leaf': 1,
                                                                         'min_samples_split': 2,
                                                                         'n_estimators': 400},
 'Nervous system disorders': {'bootstrap': False,
                              'max_depth': None,
                              'max_features': 'log2',
                              'min_samples_leaf': 1,
                              'min_samples_split': 5,
                              'n_estimators': 300},
 'Pregnancy, puerperium and perinatal conditions': {'bootstrap': True,
                                                    'max_depth': 180,
                                                    'max_features': 'sqrt',
                                                    'min_samples_leaf': 1,
                                                    'min_samples_split': 2,
                                                    'n_estimators': 400},
 'Psychiatric disorders': {'bootstrap': False,
                           'max_depth': 160,
                           'max_features': 'log2',
                           'min_samples_leaf': 1,
                           'min_samples_split': 10,
                           'n_estimators': 770},
 'Renal and urinary disorders': {'bootstrap': False,
                                 'max_depth': 60,
                                 'max_features': 'log2',
                                 'min_samples_leaf': 2,
                                 'min_samples_split': 5,
                                 'n_estimators': 430},
 'Reproductive system and breast disorders': {'bootstrap': False,
                                              'max_depth': 140,
                                              'max_features': 'sqrt',
                                              'min_samples_leaf': 5,
                                              'min_samples_split': 2,
                                              'n_estimators': 200},
 'Respiratory, thoracic and mediastinal disorders': {'bootstrap': True,
                                                     'max_depth': 180,
                                                     'max_features': 'log2',
                                                     'min_samples_leaf': 1,
                                                     'min_samples_split': 5,
                                                     'n_estimators': 470},
 'Skin and subcutaneous tissue disorders': {'bootstrap': False,
                                            'max_depth': 120,
                                            'max_features': 'log2',
                                            'min_samples_leaf': 1,
                                            'min_samples_split': 5,
                                            'n_estimators': 900},
 'Surgical and medical procedures': {'bootstrap': False,
                                     'max_depth': 80,
                                     'max_features': 'sqrt',
                                     'min_samples_leaf': 1,
                                     'min_samples_split': 5,
                                     'n_estimators': 370},
 'Vascular disorders': {'bootstrap': False,
                        'max_depth': 140,
                        'max_features': 'log2',
                        'min_samples_leaf': 1,
                        'min_samples_split': 5,
                        'n_estimators': 870}}